language: python

# sudo false implies containerized builds
sudo: false

python:
  - 3.6

env:
  global:
    # List package dependencies for conda
    - CONDA_DEPS="docopt gitpython clint pytest pytest-cov coverage"
    # List package dependencies for pip 
    - PIP_DEPS="cookiecutter inquirer schema ruamel.yaml"
    # package name for test invocation
    - PACKAGENAME="masonry"

before_install:
# Here we download miniconda and install the dependencies
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda create -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- conda install -c conda-forge $CONDA_DEPS
- pip install $PIP_DEPS
- pip install codecov

install:
- cd package
- python setup.py install
- cd ..

script:
- pytest --verbose --cov-report term --cov=$PACKAGENAME --ignore=package/tests/data/ --ignore package/tests/example_templates package/tests/

after_success:
- codecov