language: python

# sudo false implies containerized builds
sudo: false

python:
  - 2.7
  - 3.5
  - 3.6

env:
  global:
    # List package dependencies for conda
    - CONDA_DEPS="cookiecutter ruamel_yaml docopt gitpython clint pytest pytest-cov coverage"
    # List package dependencies for pip 
    - PIP_DEPS = "inquirer"
    # package name for test invocation
    - PACKAGENAME="stonemason"

before_install:
# Here we download miniconda and install the dependencies
- export MINICONDA=$HOME/miniconda
- export PATH="$MINICONDA/bin:$PATH"
- hash -r
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -f -p $MINICONDA
- conda config --set always_yes yes
- conda update conda
- conda info -a
- conda create -n testenv python=$TRAVIS_PYTHON_VERSION
- source activate testenv
- conda install $CONDA_DEPS
- pip install $PIP_DEPS
- pip install codecov

install:
- python setup.py install

script:
- pytest --verbose --cov-report term --cov=$PACKAGENAME --ignore=package/tests/data/ package/tests/

after_success:
- codecov