name: {{cookiecutter.project_name}}
channels:
- defaults
- conda-forge
dependencies:
# Core 
- python={{cookiecutter.python_version}}
- python-dotenv
# 3rd Party
{%- for lib in cookiecutter.python_libraries.split(' ') %}
{%- if lib != "NONE" %}
- {{lib}}
{% endif %}
{%- endfor %}