package:
  name: "{{cookiecutter.package_name}}"
  version: {% raw %}"{{ environ.get("GIT_DESCRIBE_TAG", '0.0.0') }}"{% endraw %} 

build:
  noarch: python
  number: {% raw %}"{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}"{% endraw %}
  string: {% raw %}"{{ environ.get("GIT_BUILD_STR", 'untagged')  }}"{% endraw %}
  entry_points:
     - "{{cookiecutter.package_name}} = {{cookiecutter.package_name}}.main:main"

source:
  path: ../../../

requirements:
  build:
    - python >=3.6.0
    - setuptools_scm >=1.15.0

  run:
    - python >=3.6.0

test:
  source_files: 
   - package/tests/data/*
   - package/tests/test_*.py

  requires: 
    - pytest >=3.0.7
    - pytest-cov >=2.3.1

  commands:
    - "{{cookiecutter.package_name}} -h"

  # A file called run_test.py is also included in the recipe that will be run
  # at test time.

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
