name: masonry
channels:
- defaults
- conda-forge
dependencies:
  # Core
  - python=3.6.1

  # 3rd party
  - cookiecutter
  - docopt
  - gitpython
  - clint

  # Testing 
  - pytest
  - pytest-cov
  - coverage

  - pip:
    - inquirer
    - ruamel.yaml
    - schema
