image: {{cookiecutter.docker_namespace}}/{{cookiecutter.project_name}}:latest

stages:
    - test
    - build

install and test source:
    stage: test
    script:
      - cd package/
      # Install Package
      - python setup.py install
      # Test Package
      - pytest
    tags:
      - docker

build src dist:
    stage: build
    script:
      - cd package/
      - python setup.py sdist --formats=zip
    artifacts:
        paths:
          - $CI_PROJECT_DIR/package/dist/
    when: on_success
    only:
      - tags
      - master
    tags:
      - docker
