image: {{cookiecutter.docker_namespace}}/{{cookiecutter.project_name}}:latest

stages:
    - test
    - build
    - deploy

install and test source:
    stage: test
    script:
      - cd package/
      # Install Package
      - python setup.py install
      # Test Package
      - pytest
    tags:
      - docker

build conda package:
    stage: build
    script:
      - cd package/
      # Build Package
      - conda build recipes/ --output-folder ../conda-package
    artifacts:
        paths:
          - $CI_PROJECT_DIR/conda-package
    when: on_success
    only:
      - tags
      - master
    tags:
      - docker

build src dist:
    stage: build
    script:
      - cd package/
      - python setup.py sdist --formats=zip
    artifacts:
        paths:
          - $CI_PROJECT_DIR/package/dist/
    when: on_success
    only:
      - tags
      - master
    tags:
      - docker

deploy:
    stage: deploy
    environment: FTP Site
    script:
        # Get Version String
        - PKG_VERSION=$(git describe --abbrev=0 --always)
        - PKG_NAME={{cookiecutter.project_name}}-$PKG_VERSION/
        - echo "$PKG_NAME"
        # Upload source distribution
        - curl -T $CI_PROJECT_DIR/package/dist/*.zip
                  ftp://ftp.mango-solutions.com/Releases/$PKG_NAME
                  --ftp-create-dirs
                  --user $FTP_USERNAME:$FTP_PASSWORD
        # Upload conda package directrory
        - cd $CI_PROJECT_DIR/conda-package
        - find . -type f -exec curl -T {} ftp://ftp.mango-solutions.com/Releases/$PKG_NAME/conda-package/{}
                                --user $FTP_USERNAME:$FTP_PASSWORD
                                --ftp-create-dirs \;
        # Upload docs
        - cd $CI_PROJECT_DIR/docs
        - find . -type f -exec curl -T {} ftp://ftp.mango-solutions.com/Releases/$PKG_NAME/{}
                                --user $FTP_USERNAME:$FTP_PASSWORD
                                --ftp-create-dirs \;
    when: manual
    only:
      - tags